In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/monthly-milk-production-pounds.csv')

In [3]:
df.columns=['Month','Production']

In [4]:
df

                                                 Month  Production
0                                              1962-01       589.0
1                                              1962-02       561.0
2                                              1962-03       640.0
3                                              1962-04       656.0
4                                              1962-05       727.0
..                                                 ...         ...
164                                            1975-09       817.0
165                                            1975-10       827.0
166                                            1975-11       797.0
167                                            1975-12       843.0
168  Monthly milk production: pounds per cow. Jan 6...         NaN

[169 rows x 2 columns]

In [5]:
df.dropna(inplace=True)

In [6]:
df

       Month  Production
0    1962-01       589.0
1    1962-02       561.0
2    1962-03       640.0
3    1962-04       656.0
4    1962-05       727.0
..       ...         ...
163  1975-08       858.0
164  1975-09       817.0
165  1975-10       827.0
166  1975-11       797.0
167  1975-12       843.0

[168 rows x 2 columns]

In [7]:
df.set_index(['Month'], inplace=True)

In [8]:
df

         Production
Month
1962-01       589.0
1962-02       561.0
1962-03       640.0
1962-04       656.0
1962-05       727.0
...             ...
1975-08       858.0
1975-09       817.0
1975-10       827.0
1975-11       797.0
1975-12       843.0

[168 rows x 1 columns]

In [9]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
X_scaled=minmax.fit_transform(df)

In [10]:
X_scaled.shape

(168, 1)

In [11]:
def train_split(data, train_size=0.7):
  rows,column=data.shape
  train_number=round(rows*train_size)
  train_data=data[:train_number]
  test_data=data[train_number:]
  return train_data,test_data

In [12]:
train,test=train_split(X_scaled, train_size=0.8)

In [13]:
df.head(15)

         Production
Month
1962-01       589.0
1962-02       561.0
1962-03       640.0
1962-04       656.0
1962-05       727.0
1962-06       697.0
1962-07       640.0
1962-08       599.0
1962-09       568.0
1962-10       577.0
1962-11       553.0
1962-12       582.0
1963-01       600.0
1963-02       566.0
1963-03       653.0

In [14]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
train_generator=TimeseriesGenerator(train,train,length=3,batch_size=1)

In [15]:
len(train)

134

In [16]:
train_generator[0]

(array([[[0.08653846],
         [0.01923077],
         [0.20913462]]]),
 array([[0.24759615]]))

In [17]:
train_generator[127]

(array([[[0.72596154],
         [0.61538462],
         [0.61778846]]]),
 array([[0.51201923]]))

In [18]:
from tensorflow.keras.layers import Dense,LSTM,Input
from tensorflow.keras.models import Sequential

In [19]:
model=Sequential([Input(shape=(3,1)),
                 LSTM(100,return_sequences=True,activation='relu'),
                 LSTM(50,return_sequences=True,activation='relu'),
                 LSTM(25,return_sequences=True,activation='relu'),
                 Dense(1)])

In [20]:
model.compile(optimizer='adam',loss='mse')

In [21]:
model.fit(train_generator,epochs=20)

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

131/131 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 0.1591
Epoch 2/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0701
Epoch 3/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0483
Epoch 4/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0322
Epoch 5/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0345
Epoch 6/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0235
Epoch 7/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0288
Epoch 8/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0205
Epoch 9/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0278
Epoch 10/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0226
Epoch 11/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0221
Epoch 12/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0250
Epoch 13/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0246
Epoch 14/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0234
Epoch 15/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0230
Epoch 16/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0242
Epoch 17/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0206
Epoch 18/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0263
Epoch 19/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0190
Epoch 20/20
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0218